// Emits dist/vars.css: every CSS variable a TwakeMuiThemeProvider would put in
// the page, as a static stylesheet for consumers that have no React to do it.
// Going through createTheme guarantees the two sets never diverge.
import { writeFileSync } from 'node:fs'

import { createTheme } from '@mui/material/styles'

import { makePalette, makeShadows, makeTypography, shape } from '../dist/index.js'

const theme = createTheme({
  cssVariables: { colorSchemeSelector: 'data-theme', cssVarPrefix: 'twake' },
  colorSchemes: {
    light: { palette: makePalette('light') },
    dark: { palette: makePalette('dark') }
  },
  typography: makeTypography(),
  shadows: makeShadows(),
  shape
})

const block = (selector, decls) =>
  `${selector} {\n${Object.entries(decls)
    .map(([prop, value]) => `  ${prop}: ${value};`)
    .join('\n')}\n}\n`

const sheets = theme.generateStyleSheets()
let css = `/* Generated by @linagora/twake-css — do not edit. */\n`
let dark = null

for (const sheet of sheets) {
  for (const [selector, decls] of Object.entries(sheet)) {
    css += block(selector, decls)
    if (selector === '[data-theme="dark"]') dark = decls
  }
}

// Follow the OS preference when the page has not chosen, the way MUI does from
// JavaScript. An explicit data-theme keeps the last word.
if (dark !== null) {
  css += `@media (prefers-color-scheme: dark) {\n${block(
    ':root:not([data-theme="light"])',
    dark
  )
    .split('\n')
    .map(line => (line === '' ? line : `  ${line}`))
    .join('\n')}}\n`
}

writeFileSync(new URL('../dist/vars.css', import.meta.url), css)
console.log(`vars.css: ${(css.match(/--twake-/g) ?? []).length} declarations`)
